spring.application.name=sgea-api

spring.datasource.url=jdbc:postgresql://localhost:5433/sgea_db
spring.datasource.username=admin
spring.datasource.password=administrador
spring.flyway.enabled=true
spring.flyway.locations=filesystem:../../../DB/sgea-db/migraciones
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
